### PR TITLE
Added max experience offsets for all (?) characters

### PR DESCRIPTION
**Pull request by borntohonk**
Offsets were documented on gbatemp ( https://gbatemp.net/threads/request-hyrule-warriors-de-editor.506421/page-3 ) , and the correct order of names were cross-referenced with an existing editor ( https://pastebin.com/dMM8bLeX )

yielding a correct list, tested to be functional for at least link:

```
3308C-3308E   "Link",
330BC-330BE   "Zelda",
330EC-330EE   "Sheik",
3311C-3311E   "Impa",
3314C-3314E   "Ganon",
3317C-3317E   "Darunia",
331AC-331AE   "Ruto",
331DC-331DE   "Agitha",
3320C-3320E   "Imp Midna",
3323C-3323E   "Fi",
3326C-3326E   "Ghirahim",
3329C-3329E   "Zant",
332CC-332CE   "Lana",
332FC-332FE   "Cia",
3332C-3332E   "Volga",
3335C-3335E   "Wizzro",
3338C-3338E   "Twili Midna",
333BC-333BE   "Young Link",
333EC-333EE   "Tingle",
3347C-3347E   "Linkle",
334AC-334AE   "Skull Kid",
334DC-334DE   "Toon Link",
3350C-3350E   "Tetra",
3353C-3353E   "King Daphnes"
```

### CODE REVIEW

**Comment by borntohonk** [comment]
I'm more or less 100% sure i made it intentional, i mean i could also add values for it being 0, but i think the intent for those who do this want max level anyways.

**Comment by WerWolv98** [comment]
Isn't the max level something that is constant throughout the game? You could use a boolean widget for that then. The off value being the default value and the on value being the new value

**Comment by borntohonk** [comment]
Setting the level does not impact stats, setting max experience does.

So i think there's a whole lot of other offsets that needs to be altered to undo the process.

**Comment by WerWolv98** [comment]
Hmm. Okay. Add a warning to those items and I'll merge it. Just something like [IRREVERSIBLE!]

**Comment by borntohonk** [comment]
irreversible

**Pull request merged**
