### PR TITLE
Octopath Traveler - Add additional values for editing

### PR DESCRIPTION
**Pull request by shahmirn**
Combining my and SleepyPrince's changes into this one PR

### CODE REVIEW

**Comment by WerWolv98** [comment]
Just tested in on my save with Cyrus and everything seems to work perfectly! I might need to add scrolling to the categories if you guys are using so many of them xD

Oh and switching from the General to the Olberic category takes quite a while the first time but that's probably just the script searching for the correct values. Other than that, thank you very much!

**Comment by shahmirn** [comment]
@WerWolv98 Yup, that's exactly the reason for the slowdown. SleepyPrince added an optimization for the categories after "Olberic", but the first one is slow.

I'm not familiar with lua at all (this is actually my first time using it), so any optimizations you can make to it would be appreciated.

**Comment by WerWolv98** [comment]
@shahmirn It's a lot worse for Hollow Knight because the save file is gigantic and the Lua JSON parser I'm using isn't that fast. The most I can do is running the whole Lua code in a different thread but that needs better support from libnx first

**Comment by shahmirn** [comment]
@WerWolv98 Is using lua a design decision or a design constraint? Just from my research of lua so far, it seems fairly simple, but its data structures and standard library seems to be fairly lacking.

I'd personally prefer to use python, but I haven't researched the Nintendo switch ecosystem at all.

**Comment by WerWolv98** [comment]
@shahmirn Lua is very light weight and actually made to be used in embedded systems. Thus it's fairly easy to implement. I don't think python can be used in the same way. With Lua we can call C functions from the scripts and call Lua functions from C which allows us to use them as modules. 

Other than that I have much more experience with Lua than with Python so that was the logical decision.

**Pull request merged**
