### PR TITLE
Hyrule Warriors Config - Materials/Rupees

### PR DESCRIPTION
**Pull request by borntohonk**
Have found and mapped all the material offsets, categorized them and confirmed the config is functional.

Have not found the offsets that makes them appear discovered, or level offsets.

### CODE REVIEW

**Comment by WerWolv98** [comment]
I can't test it since I don't have Hyrule Warriors for the Switch but the config look good AFAIKT. Thanks a lot!

**Comment by borntohonk** [comment]
I've tested it myself, with both my own save and a more progressed save I've found on gbatemp.

It displays properly and functions.

**Comment by borntohonk** [comment]
hyrulewarriors

**Comment by WerWolv98** [comment]
Fixed it thanks. Looks good other than that!

**Comment by WerWolv98** [comment]
@borntohonk Your file caused multiple save file corruptions for different people so I removed it for now from the repo. Could you take a look at that? I'll re-add it once it's fixed

**Comment by borntohonk** [comment]
I noticed the same, that's not the scripts fault tho.

It writes to the save properly. I'm experiencing the same issue .NSP installed hyrule warriors.

either it's an anticheat function, or it's not working as intended. It reverts to the edited save. Almost as if it's set to read only.

**Comment by WerWolv98** [comment]
That actually sounds like the file has a CRC or a hash of the whole file in the header of the file which breaks when editing the file. If so I would have to write a separate script for binary files with a hash. Can you check that?

**Comment by borntohonk** [comment]
For now I'm going to assume it's an anti-piracy function / anti-cheat function, or edizon somehow setting the game to read only since the save reverts to "previous state" if you press home, close game and restart game. It returns to the edited save, with nothing changed.

This thread documents doing the exact same, without these issues, by manually editing the offsets.

https://gbatemp.net/threads/request-hyrule-warriors-de-editor.506421/

**Comment by WerWolv98** [comment]
It might save the game into two files. If one is corrupted, it resets itself from the second one and the corruption occures because the hash mismatches. This is no real anti-cheat function since it can be easily worked around. If it exists, it is an anti-corruption measure. You could check by backing up your saves, editing them, creating a second backup and then comparing and checking if the changes have been made correctly. I can't really help because I don't have the game. All I can do is assist you

**Comment by borntohonk** [comment]
the second save is adventure mode maps.

**Comment by WerWolv98** [comment]
Might also be in the same file. I don't know how the game does it

**Comment by borntohonk** [comment]
Doesn't really explain why these people on gbatemp had no issues. I'm more or less sure it's an anti-piracy function. Probably detects bad cert.

**Comment by WerWolv98** [comment]
If it's only caused by SX OS then I'm fine. I already said that we're not supporting it. But if it was caused by that, you wouldn't be able to make or save progress in the game either when pirating it

**Pull request merged**
